# Generated by Django 3.2.6 on 2022-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
